version: "3.3"

services:
  zimbra:
    image: zimbra/zcs-foss:genesis
    build:
      context: "./"
      dockerfile: "./Dockerfile"
    deploy:
      mode: replicated
      endpoint_mode: dnsrr
      replicas: 1
      placement:
        constraints:
          - node.role == worker
    entrypoint:
      - /zimbra/init
    env_file: .env
    hostname: zimbra

networks:
  default:
    driver: overlay
    ipam:
      config:
        - subnet: 10.0.1.0/24
