version: "3.2"

services:
  zimbra:
    image: zimbra/zcs-foss:genesis
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == worker
    entrypoint:
      - /bin/sleep
      - infinity
    env_file: .env
    hostname: zimbra-1

  genesis:
    image: ubuntu:16.04
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == worker
    env_file: .env
    entrypoint:
      - /bin/sleep
      - infinity
    depends_on:
      - zimbra
    hostname: genesis

networks:
  default:
    driver: overlay
    ipam:
      config:
        - subnet: 10.0.1.0/24
