version: "3.2"

services:
  zimbra:
    image: zimbra/zcs-foss:latest
    env_file: .env
    entrypoint:
      - /zimbra/init
    container_name: zimbra
    volumes:
      - type: volume
        source: opt_zimbra
        target: /opt/zimbra
        volume:
          nocopy: false
    hostname: ${ZIMBRA_HOST_NAME}
    networks:
      default:
        ipv4_address: 10.0.1.3
    ports:
      - "7071:7071"
      - "8143:143"
      - "8443:443"
      - "8993:993"

networks:
  default:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.0.1.0/24

volumes:
    opt_zimbra:
